name: indexer_new
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  sqlite3: ^2.7.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
